export const tweets = [
  {
    name: "Cat Lover",
    username: "@CatLover",
    body: "My black cat, 15 years at my side: wise, independent and affectionate in her own way. Her purr and look say it all. 😺 ❤️",
    img: "https://avatar.vercel.sh/catlover",
    verified: true,
    timestamp: "3:51 PM · Dec 12, 2009",
    comments: "1,108",
    retweets: "29.7K",
    likes: "301.2K",
    bookmarks: "28",
  },
  {
    name: "Coder Life",
    username: "@CoderLife",
    body: "Being a dev means turning ideas into reality. Code, music, and many sleepless nights fixing bugs. 🤖 💾",
    img: "https://avatar.vercel.sh/coderlife",
    verified: true,
    timestamp: "12:07 PM · Sep 27, 2024",
    comments: "2,945",
    retweets: "75.1K",
    likes: "1.19M",
    bookmarks: "14.9K",
  },
  {
    name: "Family First",
    username: "@FamilyFirst",
    body: "Family means love, laughter, and unconditional support—plus nothing beats a homemade meal shared with those who matter most. 😊 🏡",
    img: "https://avatar.vercel.sh/familyfirst",
    verified: true,
    timestamp: "9:45 AM · Dec 26, 2014",
    comments: "1,205",
    retweets: "45.9K",
    likes: "981.1K",
    bookmarks: "9.1K",
  },
  {
    name: "F1 Fan",
    username: "@F1Fan",
    body: "F1 is all about speed, strategy and adrenaline. Every race is a sign that everything can be unpredictable. 🏁 🏎️",
    img: "https://avatar.vercel.sh/f1fan",
    verified: true,
    timestamp: "8:58 PM · Dec 06, 2020",
    comments: "986",
    retweets: "22.6K",
    likes: "606.4K",
    bookmarks: "4.1K",
  },
  {
    name: "In Love",
    username: "@InLove",
    body: "Having someone special is the best: love, support, and unique moments that make everything better. 😍 💕",
    img: "https://avatar.vercel.sh/inlove",
    verified: true,
    timestamp: "2:50 PM · Feb 13, 2023",
    comments: "8,901",
    retweets: "89K",
    likes: "2.09M",
    bookmarks: "17.8K",
  },
  {
    name: "Music Addict",
    username: "@MusicAddict",
    body: "Music is always there: it inspires, motivates, and accompanies every moment. Life needs a great soundtrack. 🎵 🎸",
    img: "https://avatar.vercel.sh/musicaddict",
    verified: true,
    timestamp: "5:30 PM · Sep 20, 2024",
    comments: "2,310",
    retweets: "60.2K",
    likes: "1.49M",
    bookmarks: "10.8K",
  },
  {
    name: "My Friends",
    username: "@MyFriends",
    body: "Nothing beats laughter, moments, and crazy adventures with friends. They always make life more fun. 🥳 🎮",
    img: "https://avatar.vercel.sh/myfriends",
    verified: true,
    timestamp: "5:35 PM · May 31, 2025",
    comments: "2,299",
    retweets: "61.1K",
    likes: "1.84M",
    bookmarks: "14.9K",
  },
  {
    name: "TARS",
    username: "@TARS",
    body: "Interstellar is art: science, emotions, and a soundtrack that leaves you traveling through time. 🚀 🪐",
    img: "https://avatar.vercel.sh/interstellar",
    verified: true,
    timestamp: "5:20 PM · Oct 26, 2014",
    comments: "9,298",
    retweets: "6K",
    likes: "1.47M",
    bookmarks: "10.7K",
  },
  {
    name: "Top Food",
    username: "@TopFood",
    body: "Mexican food is on another level: tacos, mole, pozole and that perfect touch of spice makes it the best food in the world. 🌶️ 🇲🇽",
    img: "https://avatar.vercel.sh/topfood",
    verified: true,
    timestamp: "5:15 PM · Nov 16, 2010",
    comments: "7,297",
    retweets: "59.9K",
    likes: "6.41M",
    bookmarks: "60.1K",
  },
  {
    name: "Wander Lust",
    username: "@WanderLust",
    body: "Traveling is the best investment: you discover, learn, and create memories that last forever. ✈️ 🏖️",
    img: "https://avatar.vercel.sh/wanderlust",
    verified: true,
    timestamp: "5:10 PM · Jan 26, 2024",
    comments: "2,296",
    retweets: "89.5K",
    likes: "5.54M",
    bookmarks: "15.5K",
  },
  {
    name: "Zero Miedo",
    username: "@ZeroMiedo",
    body: "Wrestling is pure passion. Heroes, villains, and the spectacle that always gives you chills. 💪 🔥",
    img: "https://avatar.vercel.sh/zeromiedo",
    verified: true,
    timestamp: "5:05 PM · Jan 13, 2025",
    comments: "2,295",
    retweets: "59.7K",
    likes: "1.44M",
    bookmarks: "10.4K",
  },
];
